version: '3'
services:
  embulk:
    build: ./embulk/
    volumes:
    - ./embulk/works/:/works/
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.6
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
    volumes:
    - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./es-data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

